services:
  hyper_eth:
    build: .
    image: hyper_eth
    container_name: hyper_eth
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
